- name: creation repertoire .ssh dans home
  ansible.builtin.file:
    path: ~/.ssh
    state: directory

- name: add sudoers
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ item }}
  with_items:
    - tarkan
    - heval
    - agri
    - ubuntu

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - netplan.io
    - git
    - vim
    - sudo
    - net-tools
    - inetutils-traceroute
    - ifupdown
    update_cache: yes

- name: Set sysctl for net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: create netplan config file
  ansible.builtin.template:
    src: network-config-netplan.j2
    dest: /etc/netplan/00-installer-config.yaml

- name: remove stack-volumes-lvmdriver-1
  community.general.lvg:
    vg: stack-volumes-lvmdriver-1
    state: absent
  register: toto

- debug:
    var: toto

- name: clone of a single branch
  ansible.builtin.git:
    repo: https://opendev.org/openstack/devstack
    dest: /home/ubuntu/devstack
    clone: yes

- name: add configurations to local.conf
  ansible.builtin.template:
    src: localconf.j2
    dest: devstack/local.conf

- name: create shellscript openrc.sh
  ansible.builtin.template:
    src: openrc-sh.j2
    dest: /usr/local/bin/openrc.sh
    mode: '0755'

- name: Change the working directory to devstack/ and execute stack.sh
  ansible.builtin.shell: stack.sh >> somelog.txt
  args:
    chdir: devstack/
  check_mode: yes















