- name: "creation repertoire .ssh dans home"
  ansible.builtin.file:
    path: ~/.ssh
    state: directory

- name: add sudoers
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ item }}
  with_items:
    - tarkan
    - heval
    - agri
    - ubuntu

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - netplan.io
    - git
    - vim
    - sudo
    - net-tools
    - inetutils-traceroute
    - ifupdown
    update_cache: yes

- name: " Add the line if it does not exist"
        lineinfile:
          path: /etc/sysctl.conf
          line: 's/#net.ipv4.ip_forward/net.ipv4.ip_forward/'
          state: present
          backup: yes
