- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - netplan.io
    - git
    - vim
    - sudo
    - net-tools
    - inetutils-traceroute
    - ifupdown
    update_cache: yes

- name: Set sysctl for net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: create netplan config file
  ansible.builtin.template:
    src: network-config-netplan.j2
    dest: /etc/netplan/00-installer-config.yaml

- name: remove stack-volumes-lvmdriver-1
  community.general.lvg:
    vg: stack-volumes-lvmdriver-1
    state: absent
  register: toto

- name: git clone devstack of a single branch
  become: true
  become_user: devstack
  ansible.builtin.git:
    repo: https://opendev.org/openstack/devstack
    dest: /home/ubuntu/devstack
    clone: yes

- name: create shellscript openrc.sh
  ansible.builtin.template:
    src: openrc-sh.j2
    dest: /usr/local/bin/openrc.sh
    mode: '0755'

- name: Create the system groups
  group:
    name: "devstack"
    state: "present"
    system: "yes"

- name: Create system user
  user:
    name: "{{devstack_user}}"
    generate_ssh_key: "yes"
    shell: "/bin/bash"
    groups: "sudo,devstack"
    createhome: "yes"
    home: "{{devstack_user_home}}"

- name: add configurations to local.conf
  become_user: devstack
  ansible.builtin.template:
    src: localconf.j2
    dest: devstack/local.conf

- name: Run stack.sh
  become: true
  become_user: devstack
  command: "{{ devstack_user_home }}/devstack-repo/stack.sh"

















